### ISSUE TITLE
crash at...configmaxxing? coretweaks?

### ISSUE THREAD

**Issue by kotmatross28729** [trollogyadherent/EyesInTheShadows#2]
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 28.12.22 14:58
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: trollogyadherent/configmaxxing/configpickers/dimension/DimensionEntryPoint
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:559)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:6492)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: trollogyadherent/configmaxxing/configpickers/dimension/DimensionEntryPoint
	at trollogyadherent.eyesintheshadows.Config.synchronizeConfigurationCommon(Config.java:333)
	at trollogyadherent.eyesintheshadows.Config.synchronizeConfigurationClient(Config.java:187)
	at trollogyadherent.eyesintheshadows.CommonProxy.preInit(CommonProxy.java:34)
	at trollogyadherent.eyesintheshadows.ClientProxy.preInit(ClientProxy.java:29)
	at trollogyadherent.eyesintheshadows.EyesInTheShadows.preInit(EyesInTheShadows.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
	... 10 more
Caused by: java.lang.ClassNotFoundException: trollogyadherent.configmaxxing.configpickers.dimension.DimensionEntryPoint
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 41 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 6
	at org.objectweb.asm.ClassReader.readShort(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at cpw.mods.fml.common.asm.transformers.DeobfuscationTransformer.transform(DeobfuscationTransformer.java:34)
	at makamys.coretweaks.optimization.transformercache.lite.CachedTransformerProxy.transform(CachedTransformerProxy.java:25)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 43 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_351, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 662104056 bytes (631 MB) / 2432516096 bytes (2319 MB) up to 7435714560 bytes (7091 MB)
	JVM Flags: 21 total; -Xms8G -Xmx8G -Xmn768m -XX:+AggressiveOpts -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSConcurrentMTEnabled -XX:ParallelGCThreads=4 -XX:+UnlockExperimentalVMOptions -XX:+ExplicitGCInvokesConcurrent -XX:MaxGCPauseMillis=50 -XX:+AlwaysPreTouch -XX:+UseStringDeduplication -XX:-OmitStackTraceInFastThrow -XX:+OptimizeStringConcat -XX:+UseAdaptiveGCBoundary -XX:NewRatio=3 -XX:+UseFastAccessorMethods -Xms2048M -Xmx7168M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_E7 98 mods loaded, 98 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCH	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCH	CodeChickenCore{1.1.6} [CodeChicken Core] (minecraft.jar) 
	UCH	NotEnoughItems{2.3.16-GTNH} [NotEnoughItems] (NotEnoughItems-1.7.10-2.3.16-GTNH.jar) 
	UCH	ClientFixer{1.0} [ClientFixer] (minecraft.jar) 
	UCH	FoamFixCore{1.0.2} [FoamFixCore] (minecraft.jar) 
	UCH	ItemBlacklist{1.2.0.8} [ItemBlacklist] (ItemBlacklist-1.7.10-1.2.0.8.jar) 
	UCH	gtnhmixins{2.0.2} [GTNHMixins] (000gtnhmixins-2.1.3.jar) 
	UCH	spongemixins{2.0.1} [SpongeMixins Loader] (000gtnhmixins-2.1.3.jar) 
	UCH	mixingasm{0.2.2} [Mixingasm] (00mixingasm-1.7.10-0.2.2 (1).jar) 
	UCH	gtnhlib{0.0.7} [GTNH Lib] (0gtnhlib-1.7.10-0.0.7.jar) 
	UCH	golemtweaks{1.0} [Golem Tweaks] (1.7.10-Golem+Tweaks-1.0.jar) 
	UCH	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) 
	UCH	Treecapitator{1.7.10} [Treecapitator] (1.7.10Treecapitator_universal_2.0.4.jar) 
	UCH	aiimprovements{0.0.1.8} [AI Improvements] (AIImprovements-1.7.10-0.0.1b8.jar) 
	UCH	angerissue{0.0.2} [Anger Issue] (angerissue-mc1.7.10-0.0.2.jar) 
	UCH	animalsPlus{1.2} [Animals+] (animalsplus-1.2.jar) 
	UCH	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) 
	UCH	antiidconflict{1.3.5} [Anti Id Conflict] (AntiIdConflict-1.3.5-1.7.10.jar) 
	UCH	AppleCore{3.2.3} [AppleCore] (AppleCore-1.7.10-3.2.3.jar) 
	UCH	falsepatternlib{0.10.13} [FalsePatternLib] (falsepatternlib-mc1.7.10-0.10.13.jar) 
	UCH	archaicfix{0.3.5} [ArchaicFix] (archaicfix-mc1.7.10-0.3.5 (1).jar) 
	UCH	backhand{1.7.10} [Backhand] (backhand-1.2.1.jar) 
	UCH	Baubles{1.0.1.10} [Baubles] (baubles-1.7.10-1.0.1.10.jar) 
	UCH	BetterAchievements{0.1.0} [Better Achievements] (BetterAchievements-1.7.10-0.1.0.jar) 
	UCH	betterburning{0.4.2} [Better Burning] (BetterBurning-1.7.10-0.4.2.jar) 
	UCH	BetterFoliage{2.0.17} [Better Foliage] (BetterFoliage-MC1.7.10-2.0.17.jar) 
	UCH	betterquesting{3.1.2-GTNH} [BetterQuesting] (BetterQuesting-1.7.10-3.1.2-GTNH.jar) 
	UCH	bq_standard{3.1.2-GTNH} [Standard Expansion] (BetterQuesting-1.7.10-3.1.2-GTNH.jar) 
	UCH	questbook{3.1.2-GTNH} [Better Questing Quest Book] (BetterQuesting-1.7.10-3.1.2-GTNH.jar) 
	UCH	cb4bq{3.1.2-GTNH} [Command Blocks for Better Questing] (BetterQuesting-1.7.10-3.1.2-GTNH.jar) 
	UCH	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.2308-universal.jar) 
	UCH	BNBGamingLib{2.3.2} [BNBGamingLib] (BNBGamingLib-2.3.2.jar) 
	UCH	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft1.7.10-4.2.3.5.jar) 
	UCH	VillageNames{4.4.3} [§6Village Names] (VillageNames-1.7.10-4.4.3.jar) 
	UCH	bugtorch{1.1.8} [BugTorch] (bugtorch-1.7.10-1.1.8.jar) 
	UCH	chocolateQuest{1.0} [Chocolate Quest] (chocolateQuest-1.7.10-1.1d.jar) 
	UCH	configmaxxing{modversion} [ConfigMaxxing] (configmaxxing-mc1.7.10-0.0.4.jar) 
	UCH	coretweaks{0.2.6_3} [CoreTweaks] (CoreTweaks-1.7.10-0.2.6_3 (1).jar) 
	UCH	MineTweaker3{3.1.0} [MineTweaker 3] (CraftTweaker-1.7.10-3.2.9.jar) 
	UCH	CustomMainMenu{1.9.2} [Custom Main Menu] (Custom_Main_Menu_Mod_1.7.10.jar) 
	UCH	CustomChestLoot{2.0.1} [Custom Chest Loot] (CustomChestLoot-1.7.10-2.0.1.jar) 
	UCH	damagetilt{0.1.0} [Damage Tilt] (DamageTilt-1.7.10-0.1.0.jar) 
	UCH	dmod{1.0.3.3} [D-Mod] (DMod-1.7.10-1.0.3.3.jar) 
	UCH	dss{a59} [dss] (DSS_a59.jar) 
	UCH	endlessids{1.4.0-beta0003} [EndlessIDs] (endlessids-mc1.7.10-1.4.0-beta0003.jar) 
	UCH	etfuturum{2.4.1} [§5§oEt Futurum Requiem] (Et_Futurum_Requiem-2.4.1.jar) 
	UCE	eyesintheshadows{modversion} [Eyes in the Shadows] (eyesintheshadows-mc1.7.10-0.0.8.jar) 
	UCH	falsetweaks{2.0.2-hotfix1} [FalseTweaks] (falsetweaks-mc1.7.10-2.0.2-hotfix1.jar) 
	UCH	fbp{2.4.1} [Fancy Block Particles] (FancyBlockParticles-1.7.x-2.4.1.jar) 
	UCH	foamfix{@VERSION@} [FoamFix] (FoamFix-1.7.10-universal-1.0.2 (1).jar) 
	UCH	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCH	FTBL{1.0.18.8-pu} [FTBLib] (FTBLib-1.7.10-1.0.18.8-pu.jar) 
	UCH	FTBU{1.0.18.7-GTNH} [FTBUtilities] (FTBUtilities-1.7.10-1.0.18.7-GTNH.jar) 
	UCH	gvc{0.6.1} [�aGliby's�f Voice Chat Mod] (GlibysVC-1.7.10-0.6.2a.jar) 
	UCH	HelpFixer{1.0.7} [HelpFixer] (HelpFixer-1.0.7.jar) 
	UCH	hodgepodge{2.0.10} [Hodgepodge] (hodgepodge-1.7.10-2.0.10.jar) 
	UCH	ImmersiveEngineering{0.7.7} [Immersive Engineering] (ImmersiveEngineering-0.7.7.jar) 
	UCH	IC2{2.2.827-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.827-experimental.jar) 
	UCH	itlt{1.0.3} [It's the little things] (itlt-1.7.x-1.0.3.jar) 
	UCH	journeymap{5.1.4p2} [JourneyMap] (journeymap-1.7.10-5.1.4p2-unlimited.jar) 
	UCH	lpb{1.0} [Loading Progress Bar] (Loading-Progress-Bar-v1.0-mc1.7.10.jar) 
	UCH	login_shield{1.7.10-2-gf6e21a7} [Login Shield] (Login_Shield-1.7.10-2-gf6e21a7.jar) 
	UCH	matmos{1.7.10-35.4.7} [MAtmos] (matmos-1.7.10-35.4.7.jar) 
	UCH	MTRM{1.0} [MineTweakerRecipeMaker] (MineTweakerRecipeMaker-1.7.10-1.1.1.jar) 
	UCH	MobProperties{1.0.2} [Mob Properties] (mobproperties-1.7.10-1.0.2.jar) 
	UCH	mkb{2.0.0} [ModernKeyBinding] (ModernKeyBinding-Forge-1.7.10-2.0.0 (1).jar) 
	UCH	Morpheus{1.7.10-1.6.21} [Morpheus] (Morpheus-1.7.10-1.6.21.jar) 
	UCH	MutantCreatures{1.4.9} [Mutant Creatures] (MutantCreatures-1.7.10-1.4.9.jar) 
	UCH	naturescompass{1.3.6-GTNH} [Nature's Compass] (naturescompass-1.7.10-1.3.6-GTNH.jar) 
	UCH	NEIAddons{1.12.14.40} [NEI Addons] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCH	NEIAddons|Developer{1.12.14.40} [NEI Addons: Developer Tools] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCH	NEIAddons|AppEng{1.12.14.40} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCH	NEIAddons|Botany{1.12.14.40} [NEI Addons: Botany] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCH	NEIAddons|Forestry{1.12.14.40} [NEI Addons: Forestry] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCH	NEIAddons|CraftingTables{1.12.14.40} [NEI Addons: Crafting Tables] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCH	NEIAddons|ExNihilo{1.12.14.40} [NEI Addons: Ex Nihilo] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCH	neiintegration{1.2.3} [NEIIntegration] (NEIIntegration-1.7.10-1.2.3.jar) 
	UCH	neodymium{0.1.6} [Neodymium] (neodymium-1.7.10-0.1.6.jar) 
	UCH	netherlicious{3.2.6} [§6Netherlicious] (netherlicious-3.2.6.jar) 
	UCH	nosecrets{1.0.0} [NoSecrets] (NoSecrets-Forge-1.7.10-1.0.0.jar) 
	UCH	notenoughpets{2.3.4} [§eNot Enough Pets] (NotEnoughPets-1.7.10-2.3.4.jar) 
	UCH	nova_craft{1.0} [§3NovaCraft§5§lRelease] (NovaCraft+Release+V1.0.2.1+(1.7.10).jar) 
	UCH	offlineauth{0.2.98} [Offline Auth] (offlineauth-mc1.7.10-0.2.98.jar) 
	UCH	harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's+HarvestCraft+1.7.10Lb.jar) 
	UCH	pathfindertweaks{1.7.10-1.0.13} [PathfinderTweaks] (PathfinderTweaks-1.7.10-1.0.13.jar) 
	UCH	translationmod{6.0.1} [Real-time translation mod] (RealTimeTranslation-6.0.1.jar) 
	UCH	RedstonePasteMod{1.6.2} [Redstone Paste] (redstone_paste_mod_1.7.10 (1).jar) 
	UCH	ResourceLoader{1.3} [Resource Loader] (ResourceLoader-MC1.7.10-1.3.jar) 
	UCH	RWG{alpha-1.3.3.2} [Realistic World Gen Alpha] (RWG-1.7.10-alpha-1.3.3.2.jar) 
	UCH	SoManyEnchantments{0.3.0} [Rin's So Many Enchantments] (SoManyEnchantments+Final(1.7.10)+V0.3.0.jar) 
	UCH	EnchExtensioner{0.3.0} [EnchExtensioner] (SoManyEnchantments+Final(1.7.10)+V0.3.0.jar) 
	UCH	trueinvisibility{0.3.0} [True Invisibility] (TrueInvisibility-0.3.0-1.7.10.jar) 
	UCH	WailaHarvestability{1.1.6} [Waila Harvestability] (WailaHarvestability-mc1.7.10-1.1.6.jar) 
	UCH	watchdog{1.7.10 - 1.0.0} [WatchDog Anti-Cheat] (WatchDog-AntiCheat-1.0.3-1.7.10.jar) 
	UCH	wawla{1.1.3-GTNH} [What Are We Looking At] (Wawla-1.7.10-1.1.3-GTNH.jar) 
	UCH	WorldSelectionAdvanced{1.7.10-8} [Advanced World Selection] (WorldSelectionAdvanced-1.7.10-8.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 527.56' Renderer: 'NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2'
	OptiFine Version: OptiFine_1.7.10_HD_U_E7
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 527.56
	OpenGlRenderer: NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

**Comment by trollogyadherent** [comment]
weird, does this happen alone? I see `at makamys.coretweaks.optimization.transformercache.lite.CachedTransformerProxy.transform(CachedTransformerProxy.java:25)` in the stacktrace

**Comment by kotmatross28729** [comment]
yes, this happens even if only EyesInTheShadows and ConfigMaxxing are present
